# Generated by Django 5.0.6 on 2024-07-05 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resin_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customize',
            old_name='phoneNumber',
            new_name='phonenumber',
        ),
    ]
