# Generated by Django 5.0.6 on 2024-07-05 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resin_app', '0002_rename_phonenumber_customize_phonenumber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customize',
            new_name='customizeModel',
        ),
    ]
