# Generated by Django 5.0.6 on 2024-07-05 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resin_app', '0003_rename_customize_customizemodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customizemodel',
            table='customizeModel',
        ),
    ]
