# Generated by Django 5.0.6 on 2024-07-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resin_app', '0004_alter_customizemodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='customize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phonenumber', models.BigIntegerField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='customizeModel',
        ),
    ]
