# Generated by Django 5.0.6 on 2024-07-07 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resin_app', '0005_customize_delete_customizemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customize',
        ),
    ]
