# Generated by Django 5.0.6 on 2024-07-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resin_app', '0006_delete_customize'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phonenumber', models.BigIntegerField()),
                ('address', models.CharField(max_length=200)),
                ('Resin', models.CharField(choices=[('A', 'Four Inch Agate Frame'), ('B', 'Four Inch Round Frame'), ('C', 'Four Inch Heart Frame'), ('D', 'Six Inch Agate Frame'), ('E', 'Six Inch Round Frame'), ('F', 'Twelve Inch Agate Frame'), ('G', '12x9 Inch Agate Frame'), ('H', '8 Inch Agate Frame')], max_length=1)),
                ('Wooden', models.CharField(choices=[('I', 'Eight Inch Frames'), ('J', 'Ten Inch Frames'), ('K', 'Twelve Inch Frames'), ('L', 'None')], max_length=1)),
                ('Keychain', models.CharField(choices=[('M', 'Photo Placed Agate Keychain'), ('N', 'Photo Placed Round Keychain'), ('O', 'Photo Placed Heart Keychain'), ('P', 'Photo Placed Rectangle Keychain'), ('U', 'Photo Placed Square Keychain'), ('Q', 'Baby Feet Keychain'), ('R', 'Alphabet Keychain'), ('S', 'Spotify Keychain'), ('T', 'None')], max_length=1)),
                ('productdesc', models.CharField(max_length=300)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
    ]
