# Generated by Django 5.0.6 on 2024-07-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resin_app', '0008_rename_keychain_orders_keychain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='resin',
            field=models.CharField(choices=[('A', 'Four Inch Agate Frame'), ('B', 'Four Inch Round Frame'), ('C', 'Four Inch Heart Frame'), ('D', 'Six Inch Agate Frame'), ('E', 'Six Inch Round Frame'), ('F', 'Twelve Inch Agate Frame'), ('G', '12x9 Inch Agate Frame'), ('H', '8 Inch Agate Frame')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='wooden',
            field=models.CharField(choices=[('I', 'Eight Inch Frames'), ('J', 'Ten Inch Frames'), ('K', 'Twelve Inch Frames'), ('L', 'None')], max_length=100),
        ),
    ]
